name: Workflow of exercise 4
run-name: Fourth workflow

on:
    push:
        branches: [ main ]
    pull_request: 
        branches: [ main ]
    workflow_dispatch:

jobs:
    ubuntu_job:
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                python-version: [3.12, 3.13]
                os: [ubuntu-latest, windows-latest,macos-latest]
        steps:
            - name: Checkout repository
              uses: actions/checkout@v6

            - name: Setup python
              uses: actions/setup-python@v6
              with:
                python-version: '3.14'

            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                python -m pip install -r requirements-dev.txt

            - name: Check code formatting
              run: python -m black mycode.py

            - name: Run tests
              run: python -m pytest test_mycode.py