name: Workflow of exercise 3
run-name: Third workflow

on:
    push:
        branches: [ main ]
    pull_request: 
        branches: [ main ]
    workflow_dispatch:

env:
    OUTER_ENV_VAR: "Outer value"
    SCOPED_ENV_VAR: "Scoped value"

jobs:
    ubuntu_job:
        env:
            INNER_ENV_VAR: "Inner value"
        runs-on: ubuntu-latest
        steps:
            - name: Evaluate outer environment variable
              run: echo "The value of outer environment variable is ${{ env.OUTER_ENV_VAR }}"
            - name: Evaluate inner environment variable
              run: echo "The value of inner environment variable is ${{ env.INNER_ENV_VAR }}"
            - name: Evaluate scoped environment variable
              run: echo "The value of scoped environment variable is ${{ env.SCOPED_ENV_VAR }}"
            - name: Evaluate secret
              run: echo "The value of secret is ${{ secrets.EDC_SECRET }}"