name: Workflow of exercise 2
run-name: Second workflow

permissions: {
    contents: read
}

on:
    push:
        branches: [ main ]
    pull_request: 
        branches: [ main ]
    workflow_dispatch:

jobs:
    ubuntu_job:
        runs-on: ubuntu-latest
        steps:
            - run: echo "Hello, I'm ubuntu-latest!"
    macos_job:
        runs-on: macos-latest
        steps:
            - run: echo "Hello, I'm macos-latest!"
    slow_job:
        timeout-minutes: 2
        runs-on: ubuntu-latest
        steps:
            - run: |
                echo "Hello, I'm slow_job!"
                sleep 30
    waiting_job:
        needs: slow_job
        runs-on: ubuntu-latest
        steps:
            - run: ls -l