name: Workflow of exercise 3
run-name: Third workflow

on:
    push:
        branches: [ main ]
    pull_request: 
        branches: [ main ]
    workflow_dispatch:

env:
    WORKFLOW_ENV_VAR: "Workflow environment variable"

jobs:
    ubuntu_job:
        env:
            JOB_ENV_VAR: "job environment variable"
        runs-on: ubuntu-latest
        steps:
            - run: echo "Two curly braces ${{ env.WORKFLOW_ENV_VAR }}"
            - name: Evaluate workflow environment variable
              run: echo "The value of env var is ${{ env.WORKFLOW_ENV_VAR }}"
            - name: Evaluate job environment variable
              run: echo "The value of env var is ${{ env.JOB_ENV_VAR }}"
            - name: Evaluate secret
              run: echo "The value of secret is ${{ secrets.EDC_SECRET }}"